### Numpy

#### NumPy is a fundamental library for scientific computing in Python. It provides support for arrays and matrices, along with a collection of mathematical functions to operate on these data structures.

In [2]:
import numpy as np

In [3]:
### create an array using numpy
### create a 1D array

arr1 = np.array([1,2,3,4,5])
print(arr1)
print(type(arr1))
print(arr1.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)


In [4]:
arr2 = np.array([1,2,3,4,5])
arr2.reshape(1,5) ## reshaping it in 2D array with 1 row and 5 columns

array([[1, 2, 3, 4, 5]])

In [ ]:
### creating 2D array

arr3 = np.array([
    [1,2,3,4,5],
    [2,3,4,5,6]
    ])
print(arr3)
print(arr3.shape)

[[1 2 3 4 5]
 [2 3 4 5 6]]
(2, 5)


In [7]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [8]:
np.arange(0,10,2).reshape(5,1)

array([[0],
       [2],
       [4],
       [6],
       [8]])

In [9]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [10]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
### Identity Matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
### Attributes of numpy array
arr = np.array([
    [1,2,3],
    [4,5,6]
])

print("Array:\n", arr)
print("Shape:\n",arr.shape)
print("Number of dimensions:",arr.ndim)
print("Size (number of elements):", arr.size)
print("Data type:", arr.dtype)
print("Item size (in bytes):",arr.itemsize)

Array:
 [[1 2 3]
 [4 5 6]]
Shape:
 (2, 3)
Number of dimensions: 2
Size (number of elements): 6
Data type: int64
Item size (in bytes): 8


In [14]:
### Numpy Vectorized Operation

arr4 = np.array([1,2,3,4,5])
arr5 = np.array([10,20,30,40,50])

### Addition
print("Addition:", arr4+arr5)

### Subtraction
print("Subtraction:", arr4-arr5)

### Multiplication
print("Multiplication:", arr4*arr5)

### Division
print("Division:", arr4/arr5)

Addition: [11 22 33 44 55]
Subtraction: [ -9 -18 -27 -36 -45]
Multiplication: [ 10  40  90 160 250]
Division: [0.1 0.1 0.1 0.1 0.1]


In [15]:
### Universal Function

arr6 = np.array([2,3,4,5,6])

## square root
print(np.sqrt(arr6))

## exponential
print(np.exp(arr6))

## Sine
print(np.sin(arr6))

## natural log
print(np.log(arr6))

[1.41421356 1.73205081 2.         2.23606798 2.44948974]
[  7.3890561   20.08553692  54.59815003 148.4131591  403.42879349]
[ 0.90929743  0.14112001 -0.7568025  -0.95892427 -0.2794155 ]
[0.69314718 1.09861229 1.38629436 1.60943791 1.79175947]


In [16]:
### Array slicing and indesxing

arr7 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])

print(arr7)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
print(arr7[1:,1:3])

[[ 6  7]
 [10 11]]


In [23]:
print(arr7[0:2,2:])

[[3 4]
 [7 8]]


In [24]:
print(arr7[1][2])

7


In [25]:
### Modify array elements
arr7[1][2] = 100
print(arr7)

[[  1   2   3   4]
 [  5   6 100   8]
 [  9  10  11  12]]


In [26]:
arr7[1:] = 100
print(arr7)

[[  1   2   3   4]
 [100 100 100 100]
 [100 100 100 100]]


In [27]:
### Statistical Concepts -- Normalization
### to have a mean of 0 and standard deviation of 1

data = np.array([1,2,3,4,5])

#Calculate the mean and the standard deviation
mean = np.mean(data)
print("Mean: ", mean)

std_dev = np.std(data)
print("Standard Deviation: ", std_dev)

# Normalize the data
normalized_data = (data - mean)/std_dev
print("Normalized data: ", normalized_data)

Mean:  3.0
Standard Deviation:  1.4142135623730951
Normalized data:  [-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [28]:
data1 = np.array([1,2,3,4,5,6,7,8,9,10])

#Mean
mean = np.mean(data1)
print("Mean: ",mean)

# Median
median = np.median(data1)
print("Median: ",median)

#Standard deviation
std_dev1 = np.std(data1)
print("Standard Deviation: ", std_dev1)

#Variance
variance = np.var(data1)
print("Variance: ", variance)


Mean:  5.5
Median:  5.5
Standard Deviation:  2.8722813232690143
Variance:  8.25


In [30]:
## Logical operation
data2=np.arange(0,11)

data2[(data2>=5) & (data2<=8)]

array([5, 6, 7, 8])